# Generated by Django 4.0.6 on 2024-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0002_festival_cartaz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='banda',
        ),
        migrations.AddField(
            model_name='festival',
            name='bandas',
            field=models.ManyToManyField(related_name='bandas', to='festivais.banda'),
        ),
    ]
