# Generated by Django 4.0.6 on 2024-04-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_remove_disciplina_area_cientifica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='curricularUnitCode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
